version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_learning_db
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: smart_learning
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
